server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&setTimeZone=utc+8'
    username: root
    password: gushiyua153426
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    database: mysql
